name: CI Pipeline
run-name: Run by ${{ github.actor }}

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: run tests
        run: go test